---
# tasks file for haproxy
- name: Installing HAProxy Service
  dnf: 
      name: haproxy
      state: present

- name: adding template
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
       
- name: starting HAProxy
  service:
      name: haproxy 
      state: restarted
      enabled: true
